name = "DDScienceBookJulia"
uuid = "17aaabce-7a6c-490f-b928-803eecc3ccfe"
authors = ["Javier Gonz√°lez Monge"]
version = "0.1.0"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.19"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
